### ISSUE TITLE
Can't clone because "aux.py" is a reserved filename on Windows.

### ISSUE THREAD

**Issue by tsbertalan** [jmbr/diffusion-maps#1]
Apparently Windows is [still a never-ending disaster](https://docs.microsoft.com/en-us/windows/desktop/FileIO/naming-a-file).

To reproduce, try to clone on Windows 10, or just try to download the raw view of aux.py directly from github (chrome will helpfully rename it to _aux.py).

**Comment by jmbr** [comment]
Thank you for pointing that out, Tom. This is fixed by 7e1c32e3236289e5121adfa8116c06c878578345.

**Comment by tsbertalan** [comment]
Thanks for fixing it, and for writing this--it's amazingly fast

**Comment by tsbertalan** [comment]
For more fun reading on this, see [here](https://threadreaderapp.com/thread/1058676834940776450.html) (and some comments [here](https://news.ycombinator.com/item?id=18374305)).

**Comment by jmbr** [comment]
Thank you, Tom!

Hahah. Yes, I remember using "copy con file.txt" instead of "cat file.txt" in MS-DOS. The special file con was akin to aux and you couldn't name anything that way.
